export const INTL = {
  ABOUT: {
    COMPANY: "О КОМПАНИИ",
    PARTNER: "Партнёрская программа",
    VACANCY: "Вакансии",
  },
  MENU: {
    TITLE_FIRST_PART: "МЕНЮ",
    TITLE_SECOND_PART: "\n",
    COSTS: "Расчет стоимости",
    SERVICES: "Услуги",
    WIDGETS: "Виджеты",
    INTEGRATIONS: "Интеграции",
    CLIENTS: "Наши клиенты",
    CASES: "Кейсы",
    LETTERS: "Благодарственные письма",
    CERTIFICATES: "Сертификаты",
    YOUTUBE: "Блог на Youtube",
    Q_A: "Вопрос / Ответ",
  },
  CONTACTS: {
    TITLE: "КОНТАКТЫ",
    PHONE: "+7 555 555-55-55",
    ADDRESS: "Москва, Путевой проезд 3с1, к 902",
  },
  LOGO: {
    MAIN: "крупный интегратор CRM в Росcии и ещё 8 странах",
  },
  HEADER: {
    SERVICES: "Услуги",
    MOB_SERVICES: "УСЛУГИ",
    SIGN_UP: "Получить консультацию",
    THEMES: "ТЕМЫ",
    SCHEDULES: "РАСПИСАНИЕ",
    CONTACTS: "КОНТАКТЫ",
    CASES: "Кейсы",
    MOB_CASES: "КЕЙСЫ",
    INTEGRATIONS: "Интеграции",
    MOB_INTEGRATIONS: "ИНТЕГРАЦИИ",
    CERTIFICATES: "Сертификаты",
    MOB_WIDGETS: "ВИДЖЕТЫ",
    WIDGETS: "Виджеты",
  },
  TITLES: {
    MAIN: "Зарабатывайте больше",
    DESCRIPTION: "Развиваем и контролируем продажи за вас",
    SUB_MAIN: "с WELBEX",
    SUB_TITLE: " БЕСПЛАТНОЙ КОНСУЛЬТАЦИЕЙ ",
  },
  SECTION: {
    WIDGETS: "ВИДЖЕТЫ",
    TEXT_WIDGETS: "30 готовых решений",
    MOB_TEXT_WIDGETS: "30 ВИДЖЕТОВ",
    DASHBOARD: "DASHBOARD",
    TEXT_DASHBOARD: "с показателями вашего бизнеса",
    MOB_TEXT_DASHBOARD: "DASHBOARD",
    SKYPE: "SKYPE АУДИТ",
    TEXT_SKYPE: "отдела продаж \nи CRM системы",
    MOB_TEXT_SKYPE: "SKYPE АУДИТ",
    DAYS: "35 ДНЕЙ",
    TEXT_DAYS: "использования CRM",
    MOB_TEXT_DAYS: "МЕСЯЦ AMOCRM",
  },
  COPYRIGHT: {
    COMPANY: "©WELBEX 2022. Все права защищены.",
    POLITICS: "Политика конфиденциальности",
  },
};
